// Regenerates prototype/data/<name>.js from the process JSON files, so the prototype
// can run straight from the file system (no server, no fetch). Includes the master SOP and
// the matcher's results (data/<name>/sops/*.json, see data/CONVENTION.md); engine.js folds them in.
//
// Usage (from the repo root):
//   node prototype/build-data.mjs                      -> bank-account-change
//   node prototype/build-data.mjs offboarding          -> any folder in data/ (or process/)
import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const names = process.argv.slice(2)
const SOURCE_FIELDS = ['id', 'title', 'type', 'system', 'author_role', 'owner_status', 'approval_status', 'date', 'country', 'client_specific', 'origin', 'last_reviewed']

// Only plain folder/file names, and the resolved path must stay inside its base folder (no path traversal).
const SAFE_NAME = /^[A-Za-z0-9._-]+$/
function inside(base, ...parts) {
  if (!parts.every((p) => SAFE_NAME.test(p) && !p.startsWith('.'))) throw new Error(`Invalid name: ${parts.join('/')}`)
  const full = resolve(base, ...parts)
  if (!full.startsWith(resolve(base) + sep)) throw new Error(`Path outside ${base}: ${parts.join('/')}`)
  return full
}

for (const name of names.length ? names : ['bank-account-change']) {
  if (!SAFE_NAME.test(name) || name.startsWith('.')) {
    console.error(`Invalid process name: ${name}`)
    process.exit(1)
  }
  const dir = ['data', 'process'].map((d) => inside(join(root, d), name)).find((d) => existsSync(d))
  if (!dir) {
    console.error(`No folder data/${name} or process/${name}`)
    process.exit(1)
  }
  const read = (...parts) => JSON.parse(readFileSync(inside(dir, ...parts), 'utf8').replace(/^﻿/, ''))
  const proc = read('process.json')
  const sources = read('sources.json')
  const claims = read('claims.json')
  const master = existsSync(inside(dir, 'master.json')) ? read('master.json') : null
  const sopDir = inside(dir, 'sops')
  const sops = existsSync(sopDir) ? readdirSync(sopDir).filter((f) => SAFE_NAME.test(f) && f.endsWith('.json')).map((f) => read('sops', f)) : []

  const out = {
    process: {
      id: proc.id,
      name: proc.name,
      client: proc.client,
      steps: proc.steps.map(({ id, order, name, criticality, description, step_owner_role }) => ({ id, order, name, criticality, description, step_owner_role })),
    },
    sources: sources.map((s) => Object.fromEntries(SOURCE_FIELDS.filter((k) => s[k] !== undefined).map((k) => [k, s[k]]))),
    claims: claims.map(({ id, step_id, source_id, value, statement, quote, matches_master }) => ({ id, step_id, source_id, value, statement, quote, matches_master })),
    master,
    sops,
  }

  mkdirSync(join(here, 'data'), { recursive: true })
  const file = join(here, 'data', `${name}.js`)
  writeFileSync(
    file,
    `// Generated by build-data.mjs from ${relative(root, dir)}. Do not edit by hand.\n` +
      `window.OURSDBRAIN_DATA = window.OURSDBRAIN_DATA || {};\n` +
      `window.OURSDBRAIN_DATA[${JSON.stringify(name)}] = ${JSON.stringify(out, null, 2)};\n`,
  )
  console.log(`Wrote ${relative(root, file)}: ${out.process.steps.length} steps, ${out.sources.length} sources, ${out.claims.length} claims, master ${master ? 'yes' : 'no'}, ${sops.length} matcher results`)
}
